name: terraform check execution plan

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: sets up terraform cli
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.2.0"

      - name: initialises terraform configuration
        run: terraform init

      - name: terraform format
        run: terrafrom fmt

      - name: terraform validate 
        run: terraform validate

      - name: checks the execution plan
        run: terraform plan

        